# Assignment 4: Data Wrangling
```
Course: ENV 700 - Environmental Data Exploration
Author: Student Name
Date: Fall 2026
```

This notebook accompanies the Python lessons on **Data Wrangling**, the second stage in the data analytics pipeline: **exploration, wrangling, analysis, and visualization**.

In this notebook, you will be working with US EPA Air Quality System (AQS) data on ozone and fine particulate matter (2.5 mm) levels recorded at its North Carolina monitoring stations for the years 2024 and 2025. The raw data files are provided as four separate CSV files: one for each pollutant-year combination. In this exercise, you will import each and wrangle them separately so that they can be combined into a single dataframe, where additional wrangling will enable comprehensive analysis of the dataset.

---
### 1. Set up your Python Session

#### ✅ 1.1 Import Packages
* Load the pathlib Path object and the Pandas package into your coding environnment

In [2]:
# 1.1 Import Packages
from pathlib import Path

import pandas as pd

#### ✅ 1.2 Set project folder variables
* Create three Path variables, one set to your project's **root folder** one set to the **raw data folder** and another to the **processed data folder**. 
* Display the the values of these three variables in your notebook.

In [3]:
# 1.2 Set project folders using relative paths
project_fldr = Path.cwd().parent
raw_fldr = project_fldr / 'data' / 'raw'
processed_fldr = project_fldr / 'data' / 'processed'
raw_fldr

WindowsPath('c:/Users/agn25/Documents/ENV700/ENV700/data/raw')

#### ✅ 1.3 Set a path to the raw data files
* Create a Path variable pointing to the four EPA AQS files found in the raw data folder: 
    - `EPAair_O3_NC2024_raw.csv`
    - `EPAair_O3_NC2025_raw.csv`
    - `EPAair_PM25_NC2024_raw.csv`
    - `EPAair_PM25_NC2025_raw.csv`

In [4]:
# 1.3 Create file path variables
O3_24_raw = raw_fldr / 'EPAair_O3_NC2024_raw.csv'
O3_25_raw = raw_fldr / 'EPAair_O3_NC2025_raw.csv'
PM_24_raw = raw_fldr / 'EPAair_PM25_NC2024_raw.csv'
PM_25_raw = raw_fldr / 'EPAair_PM25_NC2025_raw.csv'

#### ✅ 1.4 Read the four files into separate dataframes
(*No need to set data types, parse dates, or perform any other specialize import functions here; we will wrangle value later.*)

In [5]:
# 1.4 Read data into dataframes
O3_24 = pd.read_csv(O3_24_raw)
O3_25 = pd.read_csv(O3_25_raw)
PM_24 = pd.read_csv(PM_24_raw)
PM_25 = pd.read_csv(PM_25_raw)

#### ✅ 1.5 Report the dimensions of each dataframe
🔥***TIP***: *Each dataframe should have a different number of records.*

In [6]:
# 1.5 Report the dimensions of each dataset
print(O3_24.shape)
print(O3_25.shape)
print(PM_24.shape)
print(PM_25.shape)
O3_24.head()

(9519, 21)
(9466, 21)
(9752, 22)
(10184, 22)

,Date,Source,Site ID,POC,Daily Max 8-hour Ozone Concentration,Units,Daily AQI Value,Local Site Name,Daily Obs Count,Percent Complete,...,AQS Parameter Description,Method Code,CBSA Code,CBSA Name,State FIPS Code,State,County FIPS Code,County,Site Latitude,Site Longitude
0,03/01/2024,AQS,370030005,1,0.028,ppm,26,Taylorsville Liledoun,17,100.0,...,Ozone,47,25860.0,"Hickory-Lenoir-Morganton, NC",37,North Carolina,3,Alexander,35.9138,-81.191
1,03/02/2024,AQS,370030005,1,0.037,ppm,34,Taylorsville Liledoun,17,100.0,...,Ozone,47,25860.0,"Hickory-Lenoir-Morganton, NC",37,North Carolina,3,Alexander,35.9138,-81.191
2,03/03/2024,AQS,370030005,1,0.038,ppm,35,Taylorsville Liledoun,17,100.0,...,Ozone,47,25860.0,"Hickory-Lenoir-Morganton, NC",37,North Carolina,3,Alexander,35.9138,-81.191
3,03/04/2024,AQS,370030005,1,0.040,ppm,37,Taylorsville Liledoun,17,100.0,...,Ozone,47,25860.0,"Hickory-Lenoir-Morganton, NC",37,North Carolina,3,Alexander,35.9138,-81.191
4,03/05/2024,AQS,370030005,1,0.045,ppm,42,Taylorsville Liledoun,17,100.0,...,Ozone,47,25860.0,"Hickory-Lenoir-Morganton, NC",37,North Carolina,3,Alexander,35.9138,-81.191

---
### 2. Wrangle individual datasets

#### ✅ 2.1 Update data types
* Convert the `Date` column in each dataframe so that values are datetime objects. 
* List the date range for the two Ozone dataframes.

In [7]:
# Convert the Date column to DateTime objects
O3_24['Date'] = pd.to_datetime (O3_24['Date'], format = '%m/%d/%Y')
O3_25['Date'] = pd.to_datetime (O3_25['Date'], format = '%m/%d/%Y')
PM_24['Date'] = pd.to_datetime (PM_24['Date'], format = '%m/%d/%Y')
PM_25['Date'] = pd.to_datetime (PM_25['Date'], format = '%m/%d/%Y')

# Print date ranges
print("O3_24:",(O3_24['Date'].min()),"to", O3_24['Date'].max())
print("O3_25:",(O3_25['Date'].min()),"to", O3_25['Date'].max())
print("PM_24:",(PM_24['Date'].min()),"to", PM_24['Date'].max())
print("PM_25:",(PM_25['Date'].min()),"to", PM_25['Date'].max())

O3_24: 2024-01-01 00:00:00 to 2024-12-30 00:00:00
O3_25: 2025-01-01 00:00:00 to 2025-12-31 00:00:00
PM_24: 2024-01-01 00:00:00 to 2024-12-31 00:00:00
PM_25: 2025-01-01 00:00:00 to 2025-12-31 00:00:00

#### ✅ 2.2 Eliminate unnecessary columns
* Subset each dataframe to include only the following columns:  
```'Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude'```

In [8]:
# 2.2 Subset columns
core_cols = ['Date', 'Daily AQI Value', 'Local Site Name', 'AQS Parameter Description', 'County', 'Site Latitude', 'Site Longitude']

O3_24_core = O3_24.loc[:, core_cols]
O3_25_core = O3_25.loc[:, core_cols]
PM_24_core = PM_24.loc[:, core_cols]
PM_25_core = PM_25.loc[:, core_cols]

#### ✅ 2.3 Update values
* For the PM2.5 datasets, fill all cells in the `AQS Parameter Description` with the string "PM2.5".  
(*All cell values in this column will be identical.*)

In [9]:
# 2.3 Update values
PM_24_core['AQS Parameter Description'] = 'PM2.5'
PM_25_core['AQS Parameter Description'] = 'PM2.5'

---
### 3. Combine datasets

#### ✅ 3.1 Confirm dataframes are set to be merged
* Ensure that column names in each dataframe are indentical

In [10]:
# 3.1 Ensure column are same across all dataframes
print('O3_24:',O3_24_core.columns)
print('O3_25:',O3_25_core.columns)
print('PM_24',PM_24_core.columns)
print('PM_25:', PM_25_core.columns)

O3_24: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
O3_25: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
PM_24 Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')
PM_25: Index(['Date', 'Daily AQI Value', 'Local Site Name',
       'AQS Parameter Description', 'County', 'Site Latitude',
       'Site Longitude'],
      dtype='str')

#### ✅ 3.2 Combine the datasets 
* Combine the datasets using Pandas' `concat()` function
* Report the dimensions of the merged dataframe. (This should be `38,921 x 7`)

In [11]:
# 3.2 Concatentate & report shape
combined_data = pd.concat((O3_24_core, O3_25_core, PM_24_core, PM_25_core), ignore_index=True)

combined_data.shape

(38921, 7)

#### ✅ 3.3 Examine the contents of the merged dataframe
* Display a sample of 10 randomly selected rows, using the random state = 42

In [12]:
# 3.3 View a sample of data
combined_data.sample(10, random_state=42)

,Date,Daily AQI Value,Local Site Name,AQS Parameter Description,County,Site Latitude,Site Longitude
26921,2024-07-20,24,Pitt Agri. Center,PM2.5,Pitt,35.641276,-77.360126
6483,2024-04-22,40,University Meadows,Ozone,Mecklenburg,35.314158,-80.713469
34315,2025-02-18,53,Remount,PM2.5,Mecklenburg,35.213171,-80.874084
12494,2025-08-08,39,Clemmons Middle,Ozone,Forsyth,36.026612,-80.341962
27781,2024-01-08,12,Old High School,PM2.5,Swain,35.498711,-83.310242
23089,2024-08-26,59,Mendenhall School,PM2.5,Guilford,36.109006,-79.802314
35024,2025-02-16,27,Spruce Pine Hospital,PM2.5,Mitchell,35.912487,-82.062082
1157,2024-08-14,40,Beaufort,Ozone,Carteret,34.884800,-76.620300
4178,2024-09-14,31,Waynesville School,Ozone,Haywood,35.507224,-82.963625
13592,2025-03-29,45,Waynesville School,Ozone,Haywood,35.507224,-82.963625

---
### 4. Wrangle the combined dataset

#### ✅ 4.1 Subset rows 
* Generate a list of local site names common to all 4 dataframes (code provided, but replace the dataframe names to match your own).
* Create a subset of the full dataset, selecting those that match these local site names.
* Report the dimensions of the resulting dataframe. (This should be `18,778 x 7`)

In [13]:
# Generate a list of local site names common to all 4 dataframes
## Create set objects from the values in the Local Site Name columns
sites_oz24 = set(O3_24_core['Local Site Name']) #<-- update dataframe name to use your 2024 Ozone dataframe
sites_oz25 = set(O3_25_core['Local Site Name'])
sites_pm24 = set(PM_24_core['Local Site Name'])
sites_pm25 = set(PM_25_core['Local Site Name'])
## Compute the intersection 
common_sites = sites_oz24 & sites_oz25 & sites_pm24 & sites_pm25
common_sites

{'Bryson City',
 'Castle Hayne',
 'Clemmons Middle',
 'Durham Armory',
 'Frying Pan Mountain',
 'Garinger High School',
 'Hattie Avenue',
 'Leggett',
 'Linville Falls',
 'Mendenhall School',
 'Millbrook School',
 'Old High School',
 'Pitt Agri. Center',
 'Rockwell',
 'West Johnston Co.'}

In [14]:
# 4.1 Subset for records with sites in common
subset_data = combined_data.loc[combined_data['Local Site Name'].isin(common_sites)]

subset_data.shape

(18778, 7)

#### ✅ 4.2 Group and summarize data 
We want a dataset that lists one record per measured pollutant per location per day. To ensure we have that, we'll group data by date, local site name, AQS parameter, and county, computing the mean daily AQI value as well as mean latitude and longitude value. 
* Group the data on the grouping variables mentioned above. 
* For each group, compute mean daily AQI value, mean latitude, and mean longitude. 
* Reset the index of the summarized dataset to restore the product to a flat dataframe.
* Report the dimensions of the dataset. (This should be `17,017 x 7`.)

In [15]:
# 4.2 Group and summarize data, then report its dimensions
grouped_data = (subset_data.groupby(['Date','Local Site Name',  'AQS Parameter Description','County']
    ).agg(
        mean_AQI = ('Daily AQI Value', 'mean'),
        mean_long = ('Site Longitude', 'mean'),
        mean_lat = ('Site Latitude', 'mean')
    ).reset_index())

grouped_data.shape

(17017, 7)

#### ✅ 4.3 Add calculated columns
* Add `Year` and `Month` columns to your dataframe, deriving values from the `Date` field.

In [16]:
# 4.3 Calculate year and month columns
grouped_data = grouped_data.assign(
    month = lambda df : df['Date'].dt.month ,
    year = lambda df : df['Date'].dt.year
).reset_index()

grouped_data.head()

,index,Date,Local Site Name,AQS Parameter Description,County,mean_AQI,mean_long,mean_lat,month,year
0,0,2024-01-01,Bryson City,PM2.5,Swain,43.0,-83.442133,35.434767,1,2024
1,1,2024-01-01,Castle Hayne,PM2.5,New Hanover,44.5,-77.838611,34.364167,1,2024
2,2,2024-01-01,Clemmons Middle,PM2.5,Forsyth,47.5,-80.341962,36.026612,1,2024
3,3,2024-01-01,Durham Armory,PM2.5,Durham,61.0,-78.904037,36.032955,1,2024
4,4,2024-01-01,Frying Pan Mountain,PM2.5,Haywood,14.0,-82.792500,35.379167,1,2024

#### ✅ 4.4 Spread AQI values into separate columns: OZone & PM2.5
* Reshape our table so that Daily AQI values for Ozone and PM2.5 data appear in separate columns.
* Reset the index of the reshaped table to restore it as a flat dataframe.
* Display the first 5 records in the resulting dataframe

In [18]:
# 4.4 Spread data so Ozone, PM2.5 daily AQI valiues occupy separate columns
grouped_data_wide = grouped_data.pivot_table(
    index = ['Date','Local Site Name', 'County', 'mean_long', 'mean_lat', 'month', 'year'],
    columns = 'AQS Parameter Description',
    values='mean_AQI'
).reset_index()

grouped_data_wide.head(10)

AQS Parameter Description,Date,Local Site Name,County,mean_long,mean_lat,month,year,Ozone,PM2.5
0,2024-01-01,Bryson City,Swain,-83.442133,35.434767,1,2024,NaN,43.0
1,2024-01-01,Castle Hayne,New Hanover,-77.838611,34.364167,1,2024,NaN,44.5
2,2024-01-01,Clemmons Middle,Forsyth,-80.341962,36.026612,1,2024,NaN,47.5
3,2024-01-01,Durham Armory,Durham,-78.904037,36.032955,1,2024,NaN,61.0
4,2024-01-01,Frying Pan Mountain,Haywood,-82.792500,35.379167,1,2024,NaN,14.0
5,2024-01-01,Garinger High School,Mecklenburg,-80.785683,35.240100,1,2024,28.0,42.0
6,2024-01-01,Hattie Avenue,Forsyth,-80.224501,36.110940,1,2024,NaN,48.0
7,2024-01-01,Leggett,Edgecombe,-77.584300,35.988278,1,2024,NaN,38.0
8,2024-01-01,Linville Falls,Avery,-81.933072,35.972347,1,2024,NaN,14.0
9,2024-01-01,Mendenhall School,Guilford,-79.802314,36.109006,1,2024,NaN,53.0

---
## 5. Save your processed dataset

#### ✅ 5.1 Save the spread dataset to a file 
* Name the spread data file `EPAair_O3_PM25_NC2425_Processed.csv`
* Save it to your processed data folder
* Do not include the dataframe index in your saved file

In [20]:
# 5.1 Save the file
processed_file = processed_fldr / "EPAair_O3_PM25_NC2425_Processes.csv"
grouped_data.to_csv(processed_file, index=False)

processed_file

WindowsPath('c:/Users/agn25/Documents/ENV700/ENV700/data/processed/EPAair_O3_PM25_NC2425_Processes.csv')

---
## 6. Summarize and explore the data

#### ✅ 6.1 Generate a month summary table
* Group the above table to compute mean Ozone and PM2.5 values for each unique site, month, year combination. Be sure to reset the index of the product. 
* Display the first 5 records of this table.

In [23]:
# 6.1 Generate a summary table and show its first 5 records
summary_table = grouped_data_wide.groupby(
    ['Local Site Name','month','year']).agg(mean_O3 = ('Ozone', 'mean'),
         mean_PM = ('PM2.5','mean')).reset_index()

summary_table.head(5)

  Local Site Name  month  year    mean_O3    mean_PM
0     Bryson City      1  2024        NaN  22.580645
1     Bryson City      1  2025        NaN  25.838710
2     Bryson City      2  2024        NaN  32.000000
3     Bryson City      2  2025        NaN  32.678571
4     Bryson City      3  2024  40.709677  30.935484

---
## 7. Submission
- Save, stage, and commit this notebook
- Push changes to your GitHub account
- Export as an HTML document
- Submit both your `.ipynb` and `.html` document to Canvas.